option("enable_asan")
    set_showmenu(true)
    set_description("Enable AddressSanitizer")
    set_default(false)
option_end()
option("enable_msan")
    set_showmenu(true)
    set_description("Enable MemorySanitizer")
    set_default(false)
option_end()
option("enable_tsan")
    set_showmenu(true)
    set_description("Enable ThreadSanitizer")
    set_default(false)
option_end()
option("socket_with_posix")
    set_showmenu(true)
    set_description("Enable POSIX sockets support (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("socket_with_winsocket")
    set_showmenu(true)
    set_description("Enable WinSock sockets support (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("socket_with_sony")
    set_showmenu(true)
    set_description("Enable Sony sockets support (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("socket_with_ioctl")
	set_showmenu(true)
	set_description("Enable ioctl-based socket configuration (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_poll")
	set_showmenu(true)
	set_description("Enable poll() support for sockets (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_select")
	set_showmenu(true)
	set_description("Enable select() support for sockets (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_gethostname")
	set_showmenu(true)
	set_description("Enable gethostname() usage (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_getaddrinfo")
	set_showmenu(true)
	set_description("Enable getaddrinfo() usage (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_getnameinfo")
	set_showmenu(true)
	set_description("Enable getnameinfo() usage (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_close_on_exec")
	set_showmenu(true)
	set_description("Enable close-on-exec flag for sockets (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_msg_dontwait")
	set_showmenu(true)
	set_description("Enable MSG_DONTWAIT flag for sockets (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_recvmmsg")
	set_showmenu(true)
	set_description("Enable recvmmsg() support (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_timestamp")
	set_showmenu(true)
	set_description("Enable SO_TIMESTAMP support (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("socket_with_nodelay")
	set_showmenu(true)
	set_description("Enable TCP_NODELAY for sockets (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("platform_has_bsd_time")
	set_showmenu(true)
	set_description("Platform has BSD time APIs (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("platform_has_bsd_ipv6")
	set_showmenu(true)
	set_description("Platform has BSD IPv6 behavior (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("build_shared")
	set_showmenu(true)
	set_description("Build ReactorMQ as a shared library (auto = disabled)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("build_tests")
    set_showmenu(true)
    set_description("Build tests (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_threads")
    set_showmenu(true)
    set_description("Enable threading support (auto = enabled)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_exceptions")
    set_showmenu(true)
    set_description("Enable exceptions (auto = disabled)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_rtti")
    set_showmenu(true)
    set_description("Enable RTTI (auto = disabled)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_console_sink")
    set_showmenu(true)
    set_description("Enable console logging sink (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_file_sink")
    set_showmenu(true)
    set_description("Enable file logging sink (auto = enabled)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("with_socket_polyfill")
    set_showmenu(true)
    set_description("Enable socket API polyfills (auto = platform default)")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("secure_socket_with_tls")
	set_showmenu(true)
	set_description("Enable TLS secure sockets (auto = derived from SSL settings)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("secure_socket_with_bio_tls")
	set_showmenu(true)
	set_description("Enable BIO-based TLS secure sockets (auto = derived from SSL settings)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("ssl_available")
	set_showmenu(true)
	set_description("SSL/TLS available on this build (auto = derived from provider)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("openssl_use_shared_libs")
    set_showmenu(true)
    set_description("SSL/TLS Use shared OpenSSL libraries")
    set_default(false)
option_end()
option("with_ue5")
	set_showmenu(true)
	set_description("Build with UE5-specific code paths (auto = disabled)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("with_o3de")
	set_showmenu(true)
	set_description("Build with O3DE-specific code paths (auto = disabled)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("platform_windows")
    set_showmenu(true)
    set_description("Force Windows platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_linux")
    set_showmenu(true)
    set_description("Force Linux platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_android")
    set_showmenu(true)
    set_description("Force Android platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_macos")
    set_showmenu(true)
    set_description("Force macOS platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_ios")
    set_showmenu(true)
    set_description("Force iOS platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_prospero")
    set_showmenu(true)
    set_description("Force Prospero (PS5) platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_nnx")
    set_showmenu(true)
    set_description("Force Nintendo NNX platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("platform_gdk")
    set_showmenu(true)
    set_description("Force Microsoft GDK platform flags")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("family_windows")
    set_showmenu(true)
    set_description("Windows family")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("family_darwin")
	set_showmenu(true)
	set_description("Darwin family (auto = platform default)")
	set_values("auto", "on", "off")
	set_default("auto")
option_end()
option("family_posix")
    set_showmenu(true)
    set_description("POSIX family")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("family_console")
    set_showmenu(true)
    set_description("Console family")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("family_nintendo")
    set_showmenu(true)
    set_description("Nintendo family")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("family_sony")
    set_showmenu(true)
    set_description("Sony family")
    set_values("auto", "on", "off")
    set_default("auto")
option_end()
option("ssl_provider")
    set_default("libressl")
    set_showmenu(true)
    set_description("SSL provider to use: system|libressl|awslc|none")
option_end()
